### ISSUE TITLE
Should add syntax highlighting to additional multiple inheritance instances.

### ISSUE THREAD

**Issue by VoR0220** [davidhq/SublimeEthereum#1]
Idk if this is a short fix or not but in I've noticed that the second multiple inheritance instance is not highlighted in this package. Small, but would be nice to have for consistency. 

Example:

contract foo is bar, zen {
************************^
******************this needs highlighting 
}

**Comment by davidhq** [comment]
Thank you, done: https://github.com/davidhq/SublimeEthereum/commit/477fc75dca760cda63e28aba8798a549221f28b5

packagecontrol has to update to 0.9.4
