### ISSUE TITLE
Special syntax highlighting for inline assembly blocks

### ISSUE THREAD

**Issue by VoR0220** [davidhq/SublimeEthereum#11]
This would be very nice to have.

**Comment by davidhq** [comment]
Provide a few examples or link to documentation please... in all issues you opened.

**Comment by davidhq** [comment]
Nevermind the previous comment ;)

**Comment by davidhq** [comment]
Fixed by @ralph-pichler in v0.9.57

**Comment by ralph-pichler** [comment]
@davidhq not yet implemented

**Comment by davidhq** [comment]
done, please test
