### ISSUE TITLE
Add support of Solidity linter

### ISSUE THREAD

**Issue by idrabenia** [davidhq/SublimeEthereum#16]
Hi guys!

We develop linter that allow to verify style guide, security and best practices issues! There is Solhint - https://github.com/protofire/solhint

Your extension is awesome, I am using it - and I think it would be a nice feature to add support of linter. 

I believe solhint will be very helpful for your project!
\- Ilya

**Comment by davidhq** [comment]
This sounds very good... I hope to be able to check the workings of `solhint` separately by your github instructions, then maybe you can prepare the integration with `SublimeEthereum` and we test it until it's working well, then release?

**Comment by davidhq** [comment]
Hi Ilya, sorry for the delay (I got a child recently)... 
I tried `solhint`, seems very nice... what do you suggest now?

Probably the best would be to make this work in the way SublimeLinter works, check pics:

<img width="278" alt="screen shot 2017-10-31 at 10 22 28" src="https://user-images.githubusercontent.com/3899/32216516-7fad5592-be25-11e7-8448-67777c4e138f.png">
<img width="510" alt="screen shot 2017-10-31 at 10 22 33" src="https://user-images.githubusercontent.com/3899/32216519-81eaa7ec-be25-11e7-8e89-0ef8ba73acf3.png">

**Comment by davidhq** [comment]
I'm closing this for now since a lot of time has passed and we didn't implement it and plus maybe this package will continue with just including syntaxes and nothing more... not sure yet. We can still discuss in the future.
