### ISSUE TITLE
Solidity sintax not working in Sublime Text

### ISSUE THREAD

**Issue by FernandoJefferson** [davidhq/SublimeEthereum#18]
I have installed Ethereum Package for Sublime Text 2/3 but it is not working
And Solidity does not appear in the options under "VIew / Syntax"
Any idea?
Thanks in advance

**Comment by FernandoJefferson** [comment]
It's working!
But the checklist provided in this link is incomplete:
https://packagecontrol.io/installation

a) Click the Preferences > Browse Packages… menu
b) Browse up a folder and then into the Installed Packages/ folder
c) Download Package Control.sublime-package and copy it into the Installed Packages/ directory
d) Restart Sublime Text

NEW:
e) Click Preferences > Package Control > Enable Package.    -   Select Etherium
f) Restart Sublime Text
g) Click View > Sintax > Solidity

**Comment by Ornataweaver** [comment]
You can change the mistake in the name. It's syntax as you know, not "sintax". It's like going to Los Vegas and being taxed. 😁

**Comment by Ornataweaver** [comment]
I have "Package Control.sublime-package" in the directory, yet it's not working for me.
Also there is no "EthereumSoliditySnippets" in 'Enable Package' option. It's already enabled.
We should reopen this issue.

**Comment by Ornataweaver** [comment]
Don't reopen the issue. It's perfectly working for me. I had mistaken this project withhttps://packagecontrol.io/packages/EthereumSoliditySnippets. :smile:

**Comment by FernandoJefferson** [comment]
It was a typing error. And I'm not a native english speaker.
The important thing is that I have solved a real problem, suggesting how to change the documentation and help people with the same problem.
Stop being ridiculous, man ...

**Comment by Ornataweaver** [comment]
I didn't mean to insult you, I was being friendly. Thank you for solving the problem.
