### ISSUE TITLE
When used from Linguist some files don't get properly highlighted

### ISSUE THREAD

**Issue by LefterisJP** [davidhq/SublimeEthereum#21]
Hello,

As you may have seen this package is now [used](https://github.com/github/linguist/pull/3973) by linguist to provide syntax highlighting for solidity files in Github.

Unless I have not understood how linguist works then there may be a problem with the grammar rules of this package. Some solidity files do not get highlighted properly in github and the problem seems to be the `/* */` (multiline comments).

In the raiden network repository we just introduced `.gitattributes` and some of our [smart contracts](https://github.com/raiden-network/raiden/tree/master/raiden/smart_contracts) are now properly highlighted while some are not.

The simplest example i can provide is this file in the raiden network repository which is not properly highlighted, presumably due to the multiline comment: 
https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/Standard_Token.sol

The same file, in my fork, with the multiline comment removed is highlighted properly:
https://github.com/LefterisJP/raiden/blob/testity/raiden/smart_contracts/Standard_Token.sol

There could also be another reason why this is happening and I may be wrong. I just want to try and find out why not all the files are properly highlighted.

**Comment by LefterisJP** [comment]
I am closing this issue as I contacted github support and they can confirm it is a caching issue on their side.

**Comment by davidhq** [comment]
Great, was just about to investigate, thank you for finding the problem elsewhere so quickly.
