### ISSUE TITLE
Highlight last item in a parameter list if separated from closing paren by a newline

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [davidhq/SublimeEthereum#24]
Currently, the last item on this list is not highlighted properly:

![image](https://user-images.githubusercontent.com/130362/42591082-8d2cca12-8513-11e8-925c-a48559d409f4.png)

It is correct if either 1) a comma is inserted after `bytes32[] s`, or 2) the newline between the `bytes32[] s` and the closing paren is deleted. However (1) is a syntax error in solidity and (2) is ugly.

**Comment by paulofelipe84** [comment]
Another one here who's missing that! Any news about it?

**Comment by davidhq** [comment]
Hi there! I'm quite sorry, finishing something important, but slowly getting back to this rewrite, see discussion here: https://github.com/davidhq/SublimeEthereum/issues/29

I hope and believe that until 15.1.18 this package could be rewritten to the new syntax parsing system.

**Comment by davidhq** [comment]
Another update, current state of capabilites:

<img width="1265" alt="screen shot 2019-01-16 at 22 11 33" src="https://user-images.githubusercontent.com/3899/51278790-d1ce4800-19db-11e9-8457-b84813db83c2.png">

I think most of big things are implemented, but I do still need to finish conditionals and loops... I hope no big issues there... So far it's 500 LOC, expect 200 or so more... old parser was 100 lines in total.

**Comment by davidhq** [comment]
done, please test

**Comment by davidhq** [comment]
Yes, it seems that `PackageControl` hack picked up [v1.1.0](https://packagecontrol.io/packages/Ethereum) already... so it should install automatically if you have packages auto-update turned on as by default, if not, update the package Ethereum manually

**Comment by paulofelipe84** [comment]
Yeah, you can see that I even removed my comment. I had to uninstall and re-install it.

It works! Thanks heaps, David!

**Comment by davidhq** [comment]
Some very minor highlighting is missing (mainly from [here](https://solidity.readthedocs.io/en/v0.5.2/units-and-global-variables.html), to be released in v1.1.1 quite soon, together with any issues you guys report by then... 

Enjoy better colors! this was harder to implement than I thought... or better said I suspected it would be hard and so I procrastinated for over a year in tackling it ^_^

Now it finally should also be easy to understand and contribute minor or major (?) enhancements . As well as being able to learn quite a lot about Solidity itself by looking at [solidity-syntax](https://github.com/davidhq/SublimeEthereum/blob/master/Solidity.sublime-syntax) file.
