### ISSUE TITLE
Error installing via Package Manager on Sublime Text 2

### ISSUE THREAD

**Issue by mickayz** [davidhq/SublimeEthereum#27]
Receive the following error in console:

Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590))) downloading https://codeload.github.com/davidhq/SublimeEthereum/zip/v1.0.3.
error: Package Control

Unable to download Ethereum. Please view the console for more details.

**Comment by davidhq** [comment]
Hi! Has this worked for you later? I think I couldn't help with this issue, maybe it was something with PackageControl's servers? Please report if you still have issues and we will investigate... I tried recently and it installed.
