### ISSUE TITLE
changing colors of inherited contracts

### ISSUE THREAD

**Issue by loziniak** [davidhq/SublimeEthereum#28]
I noticed three different colour schemes for inherited contracts declaration:
1. contracts with only-letter names
1. contract with digits in its name and succeeding contracts
1. contract with arguments in parentheses and succeeding contracts

Is this intentional? Or maybe because of my old SublimeText?

(SublimeText build 3059, SublimeEthereum fresh cloned from Github)

**Comment by davidhq** [comment]
Hi! Sorry for late response, it is not intentional, rewrite of syntax highlighter is currently being done and this comment will be considered after it is done. Will write back before or after holiday season. Thank you

**Comment by davidhq** [comment]
done, please test
