### ISSUE TITLE
Request: Library highlighting

### ISSUE THREAD

**Issue by VoR0220** [davidhq/SublimeEthereum#3]
Do you think it would be possible at all to get highlighting similar to that of a contract with a library?

**Comment by davidhq** [comment]
Hi! Sorry I was on a longer trip in Asia.

Not sure what you mean? "contract with a library" ?

**Comment by VoR0220** [comment]
Lol. I went ahead and made my own package since you were away for a while. But yeah library contracts are now part of the syntax. There's been a lot of changes since you've been gone. If you want a link to what I did, you can checkout here:

https://github.com/VoR0220/SoliditySyntaxHighlighting

I would love if someone were to make this better in some way or just make the color selection...better :)

**Comment by davidhq** [comment]
haha yes, I know ;) I actually saw your msg but kept postponing, I was reading a lot of books etc, was afraid to jump back into dev and maintenance... but now I will, in 1-2 weeks after coming back from FOSDEM.. I'll make everything up-to-date, and will check what you have done.. if need be, can I borrow your code? Or you can send pull request to my project if you don't plan to put develop yours and/or put it on packagecontrol ?

**Comment by VoR0220** [comment]
You can make full use of mine, by all means. I don't intend to develop much more in it, but I would also like to discuss it with you in terms of color schemes and what have you because I'm a picky sonofabitch like that.

**Comment by davidhq** [comment]
okay, perfect... we discuss when I get back home next week.... until then!

**Comment by u2** [comment]
Looks great! :+1:
