### ISSUE TITLE
Incorrect highlighting of function names beginning with return

### ISSUE THREAD

**Issue by G-GFFD** [davidhq/SublimeEthereum#31]
![screenshot_20190131_143452](https://user-images.githubusercontent.com/12546045/52057548-8f714300-2565-11e9-8ca6-d047b6f2b485.png)

calling a function containing return at the beginning of it's name highlights the `return` part in red. This should not be the case, the complete function name should be in light blue as it is a normal function call.  `return` should only be highlighted in red when it actually is the return statement.

Issue probably applies with other keywords too.

**Comment by davidhq** [comment]
You are correct... this is to be tackled (and it's an easy fix) when everything else settles just a bit more, enhancement reports are still arriving... thank you for patience.

**Comment by davidhq** [comment]
fixed in v1.1.9
