### ISSUE TITLE
Syntax highlighting breaks on modifiers with certain types of arguments

### ISSUE THREAD

**Issue by mrice32** [davidhq/SublimeEthereum#33]
The syntax highlighting seems to break if there's a type in the list of arguments for a modifier that has a `.` in it.

Here's a minimal example:
```
/*
  Test
*/
pragma solidity ^0.5.0;

library A {
    struct MyStruct {
        uint value;
    }
}

library B {
    modifier modifierExample(A.MyStruct storage s) {
        require(s.value == 6);
        _;
    }

    function doSomething(A.MyStruct storage s) modifierExample(s) {

    }
}
```

I've attached a screenshot of the highlighting for this contract.

![screen shot 2019-02-14 at 5 37 38 pm](https://user-images.githubusercontent.com/11791551/52822366-7eedbc00-307f-11e9-8a00-b6cbcc5cd36b.png)

**Comment by davidhq** [comment]
Thank you. I hope [this](https://github.com/davidhq/SublimeEthereum/commit/3ba0d583e25d9987ad65f63427d5de7e52a2d7aa) fixes it well... if not, please report back

**Comment by mrice32** [comment]
That seems to have fixed it. Thank you for your help - this package is awesome!
