### ISSUE TITLE
Incorrect highlighting of variable names beginning with return

### ISSUE THREAD

**Issue by mrice32** [davidhq/SublimeEthereum#34]
Not sure if this is the same issue as #31, but I wanted to make sure it was called out specifically - when a line inside a function begins with the word `return`, it seems to always be highlighted red, regardless of whether that is the first part of a variable name or function. I've attached a screenshot for the variable name variant of this issue.

![screen shot 2019-02-22 at 5 41 34 pm](https://user-images.githubusercontent.com/11791551/53275575-8fc6af00-36c9-11e9-9d82-131722033265.png)

**Comment by davidhq** [comment]
fixed in v1.1.9
