### ISSUE TITLE
Highlighter fails on arrays 

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#36]
Package fails for  arrays:
```
    uint[] public array = [0,1,2];
```
only the first element is correctly colored.

**Comment by davidhq** [comment]
Can you post a screenshot? In my editor it looks like this:
<img width="234" alt="screen shot 2019-02-28 at 20 43 20" src="https://user-images.githubusercontent.com/3899/53593666-8b9f0380-3b99-11e9-985e-d03cd54339ef.png">

so I don't quite see the issue?

**Comment by eMarchenko** [comment]
for me it doesn't highlight elements after the first one. I'll do screenshot soon.

**Comment by eMarchenko** [comment]
![array_issue](https://user-images.githubusercontent.com/7409234/53637713-f0f40280-3c34-11e9-94c9-defd8b73d622.png)

**Comment by davidhq** [comment]
ok, got it... because it's not inside a function... will check tomorrow or so

**Comment by davidhq** [comment]
fixed in v1.1.12

**Comment by davidhq** [comment]
fix broke something else, need to take a better look, rollback until then (soon)

**Comment by davidhq** [comment]
https://github.com/davidhq/SublimeEthereum/issues/39
