### ISSUE TITLE
Highlighter fails on integer contstants

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#37]
scientific notation:
```
int256 public i1 = 1e10;
int256 public i2 = 1e-1 * 100;
int256 public i3 = 1e1 hours;
int256 public i4 = 123_000;
int256 public i5 = 1_2e345_678 / 1_2e345_677;
```
all cases have some issues.

Solidity [documentation](https://solidity.readthedocs.io/en/develop/types.html#rational-and-integer-literals).

**Comment by davidhq** [comment]
<img width="334" alt="screen shot 2019-02-28 at 20 42 45" src="https://user-images.githubusercontent.com/3899/53593618-6d390800-3b99-11e9-833e-6b1a9272b03a.png">

is this ok? Will push the changes soon

**Comment by eMarchenko** [comment]
Yep, looks nice!

**Comment by davidhq** [comment]
published in v.1.1.11
