### ISSUE TITLE
Some highlighter problems inside assembly

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#40]
Some instructions should be colored but they are not:
![Screenshot (8)](https://user-images.githubusercontent.com/7409234/54437279-596ad580-4745-11e9-9aea-c71dbc909d3f.png)

* `delegatecall`
* `returndatacopy` and `returndatasize`
* `switch`, `case`, and `default`.

same code so you can copy it:
```solidity
pragma solidity ^0.4.24;

contract Router {
    function() external payable {
        address delegate = address(0x123);
        assembly {
            let ptr := mload(0x40)
            calldatacopy(ptr, 0, calldatasize)
            let result := delegatecall(gas, delegate, ptr, calldatasize, 0, 0)
            let size := returndatasize
            returndatacopy(ptr, 0, size)
            switch result
            case 0 {revert(ptr, size)}
            default {return (ptr, size)}
        }
    }
}
```

**Comment by davidhq** [comment]
Thank you, fixed in `v1.1.18`... Added `revert` as well... plus found some others missing which will be added according to latest documentation in the next few days.
