### ISSUE TITLE
Highlighter fails on strings with mix of `'` and `"`

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#41]
```Solidity
string s1 = "1'1";
string s2 = "2'2";
```

![example](https://user-images.githubusercontent.com/7409234/54612556-38b6be80-4a6a-11e9-840d-494da8aee9b1.png)

**Comment by davidhq** [comment]
<img width="149" alt="Screen Shot 2019-05-21 at 11 57 48" src="https://user-images.githubusercontent.com/3899/58086880-c3797e00-7bbf-11e9-873c-fcbb82948da1.png">

fixed in `v1.1.20` ... along with other open issues
