### ISSUE TITLE
Highlighter fails on "decimal" constants

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#43]
```Solidity
pragma solidity ^0.5.0;
contract Test {
    function foo() internal pure {
        uint i = 0.1e0 ether;
        uint j = .1e0 ether;
    }
}
```
![example](https://user-images.githubusercontent.com/7409234/54680750-bb4b8680-4b1b-11e9-9743-477a135c160b.png)

**Comment by davidhq** [comment]
thank you for the latest reports... will tackle all, might take a few days...
