### ISSUE TITLE
Blocks inside a function break syntax highlighting

### ISSUE THREAD

**Issue by nventuro** [davidhq/SublimeEthereum#47]
Solidity allows having blocks (delimited by braces) inside a function, which are useful to limit scope of local variables. The Solidity syntax highlighting breaks when these are encountered.

Code example to reproduce:
```solidity
pragma solidity ^0.5.5;

contract Test {
    function foo(uint256 a) public {
      a = 2 + 3;

      bar();

      {
        uint256 b = a - 3;
        if (b == 5) {
          revert();
        }
      }

      bar();
    }

    function bar() public {

    }
}
```

This renders as follows in v1.1.22:
![image](https://user-images.githubusercontent.com/2530770/59942890-4009b180-9437-11e9-8b4e-ee62c443cbf1.png)

**Comment by davidhq** [comment]
I'm on holiday and is late here but this was easy to do, so to clear the pipeline I implemented the fix:
https://github.com/davidhq/SublimeEthereum/commit/d10aa832693047b0ff2847c75e25d5a7cf16834c

the trick is that I'm quite certain that this didn't break something else but still not 100% so as a favour if you could check a little bit in various contract examples if everything still seems to work as before :)

thank you for the report and good night

**Comment by nventuro** [comment]
Thank you so much for the prompt response! The fix works perfectly on both the failing contract and all other source files I tested. Will let you know if something breaks :)
