### ISSUE TITLE
Wrong highlighting on anonymous function arguments with location

### ISSUE THREAD

**Issue by nventuro** [davidhq/SublimeEthereum#48]
Hello again! Thanks for working on such a great plugin :)

Starting on Solidity v0.5.0, some types (e.g. `bytes`) require a mandatory location attribute (`memory`, `storage` or `calldata`). This confuses the highlighter when a function argument has no name, making it believe the storage location is the name.

E.g. the following code:
```solidity
pragma solidity ^0.5.5;

contract Test {
  function foo(bytes memory a, uint256 b, uint256, uint256 d) public {}

  function bar(bytes memory, uint256 b, uint256, uint256 d) public {}
}
```

is highlighted as follows:
![image](https://user-images.githubusercontent.com/2530770/61902662-f5c59580-aef8-11e9-9544-db3cb281b892.png)

(note that GitHub's highlighting seems to have the same issue, namely, on the `bar` function `memory` is highlighted as if it was an argument name)

**Comment by davidhq** [comment]
Thank you! will take a look in the next few days

**Comment by davidhq** [comment]
Fixed https://github.com/davidhq/SublimeEthereum/commit/ee1a818d732229e8dc74adce8e7043d12a118e1f .. thank you for this report, it was quite important omission

**Comment by nventuro** [comment]
Awesome, thanks!
