### ISSUE TITLE
Any plan to make one for Atom?

### ISSUE THREAD

**Issue by brent-riva** [davidhq/SublimeEthereum#49]
I saw that this _very popular_ atom plugin: https://github.com/caktux/language-ethereum used your repo a few years ago to add Ethereum language support to atom. However, it has not been updated in years. Have you considered translating this sublime plugin to also an atom plugin? Ideally, if this caktux person has done the translation already, you can look at what they did and learn to do it yourself. It would be cool if you got the credit for it too since it used your repo!

**Comment by brent-riva** [comment]
I'm seeing that this was the tool/guide used: https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843

**Comment by davidhq** [comment]
Hi! Thank you for writing... this is a bit "complicated" but maybe we can tackle the issue together somehow... Some time ago (year or even more) I tried contacting caktux regarding the updates, actually here: https://github.com/caktux/language-ethereum/issues/4

There are probably two issues that have to be solved to do anything:

- actually convert the latest version to Atom again, using the tool... at the moment I don't have time to play with this, maybe soon, but only if the next requirement is met :

- how to actually deploy the updated syntax to Atom if this person doesn't respond? If you have some time, can you investigate? Or is doing the parallel plugin with some other name the only way?

Also, SublimeText allows stack-based grammars and this repo uses the new system (there is a branch with older regex based approach that Atom supports and Linguist on GitHub is using).

So, that's it from me for now, in the next ~2 weeks cannot offer more ideas so please help investigating what is possible and I'll help gladly later.

**Comment by davidhq** [comment]
Additional question: Atom itself is not going away or anything like that now that Microsoft owns GitHub since MS has it's own popular editor VSCode?

**Comment by brent-riva** [comment]
> Additional question: Atom itself is not going away or anything like that now that Microsoft owns GitHub since MS has it's own popular editor VSCode?

That's.... actually a great question. I would assume not, because of how much has been put into it and the community support it has. At the very least, an update would be cool since it's been _years_ since the last one 👀 . 

> how to actually deploy the updated syntax to Atom if this person doesn't respond? If you have some time, can you investigate? Or is doing the parallel plugin with some other name the only way?

I think it would have to be its own plugin, if he/she is not responding. I think they technically own the package, otherwise I (Trudy) could wreck all hell in packages and ruin atom for everybody by uploading malicious package updates.
