### ISSUE TITLE
Add support for Solidity 0.6 features

### ISSUE THREAD

**Issue by nventuro** [davidhq/SublimeEthereum#50]
The 0.6 release introduced a couple new keywords and features that break syntax highlighting:

 * the new `receive` and `ether` keywords replace the old anonymous fallback function
 * functions can be annotated to be `virtual`, and `override` must be added when overriding
 * contracts can be `abstract`
 * the `try/catch` statement is a whole new beast: https://solidity.readthedocs.io/en/latest/control-structures.html#try-catch

A summary of the changes can be found here: https://solidity.readthedocs.io/en/latest/060-breaking-changes.html

**Comment by davidhq** [comment]
Hi @nventuro ! Thank you for the report, always helpful ...

The main issue now is to see how syntax highlighting could be versioned and take into account the version pragma directive... 

Or if this is too cumbersome what would you suggest as a solidity developer "in the loop"? Just go with latest version and break the old contracts syntax highlighting? Thank you for any advice here as well...

**Comment by nventuro** [comment]
Hm, I suspect there'll be overlap of 0.5 and 0.6 for some time, at least a couple months. I see two possible paths forward:

 1. the 'right' thing to do would be to parse the pragma directive and choose which syntax to use, but I'm not sure how easy it'd be to add this given the plugin's architecture. Note that there are some edge cases: it is possible to write contracts with pragmas that'll accept both major versions of the compiler, in which case the best thing would probably be to default to the 'old' 0.5 style.
 2. add support for 0.6 and be done with it. 0.6's syntax is a superset of 0.5's in many ways: the main non-backwards-compatible changes are the new keywords, but I doubt there are many old contracts out there that used these as identifiers. In any case, you could work around this by releasing this under 1.2 (or 2.0), and pointing users for which the newer syntax breaks towards the outdated (current) release.

I'd personally go with option 2, I'm not sure the value added is worth the extra complexity, and like I said, 0.6 highlighting on 0.5 code should be fine in 99% of the cases.

Thank you so much for your work on this!

**Comment by davidhq** [comment]
Hi @nventuro ! Sorry for delay, I plan to tackle this shortly ...

**Comment by davidhq** [comment]
Hi @nventuro ! Can you find an example of `abstract` contracts ?

Otherwise I have added the rest, including try-catch ... When https://packagecontrol.io/packages/Ethereum updates to `1.1.25` please test a little bit and let me know if there are any issues.

<img width="609" alt="Screen Shot 2020-04-09 at 19 57 13" src="https://user-images.githubusercontent.com/3899/78925817-54896a00-7a9c-11ea-85f4-b2b26725b222.png">

**Comment by nventuro** [comment]
That's great, thanks!

`abstract` is simply added before the `contract` keyword, like here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Pausable.sol#L14

**Comment by davidhq** [comment]
Ok thank you, I thought so but couldn't confirm by quick look.

In `v1.1.26` abstract keyword for contracts is added.

The only remaining thing I'm not sure is `override` -- can you provide a few correct examples with context for this as well in case it currently does not work ok ?

Thank you

**Comment by nventuro** [comment]
There's only two variants for `override`: it can be found by itself, like here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Pausable.sol#L22

Or it can also list a number of identifiers in parenthesis, like here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/deploy-ready/ERC20MinterPauser.sol#L82

**Comment by davidhq** [comment]
Thank you!

So I think for now it's good enough? (I still have to update the GitHub fork of the highlighter)...

In SublimeText I see:

<img width="823" alt="Screen Shot 2020-04-11 at 15 37 58" src="https://user-images.githubusercontent.com/3899/79045271-8d475180-7c0a-11ea-8c80-49f1a1d7ecc3.png">

<img width="724" alt="Screen Shot 2020-04-11 at 15 38 06" src="https://user-images.githubusercontent.com/3899/79045272-91736f00-7c0a-11ea-8338-cb1704ca8a39.png">

**Comment by davidhq** [comment]
Another thing:

> the new `receive` and `ether` keywords replace the old anonymous fallback function

Was that a typo ? 

Docs say:

The unnamed function commonly referred to as “fallback function” was split up into a new fallback function that is defined using the `fallback` keyword and a receive ether function defined using the `receive` keyword.

So are the keywords actually `receive` and `fallback` OR `receive` and `ether`? 

I think this is then the last thing before closing this issue....

**Comment by nventuro** [comment]
>So are the keywords actually receive and fallback OR receive and ether?

Yes, sorry! I was looking at an old changelog, before the final rename. The actual keywords are `receive` and `fallback`.

**Comment by nventuro** [comment]
It looks like the `override(x)` syntax broke highlighting on v1.1.26:

![image](https://user-images.githubusercontent.com/2530770/79142786-70d62100-7d92-11ea-91ef-5c27ef627028.png)

**Comment by davidhq** [comment]
OK yes, I see now... Later today everything will be fixed and I close this ticket..

Thank you again for help and sorry for big delay, had some unexpected big tasks in between.

Looking forward for next report(s) when the time comes!

**Comment by davidhq** [comment]
https://github.com/davidhq/SublimeEthereum/tree/v1.1.28

**Comment by nventuro** [comment]
Everything now works great, thank you very much for your work!

**Comment by nventuro** [comment]
It seems my prior testing was incomplete, I found another instance where the highlighter breaks:

![image](https://user-images.githubusercontent.com/2530770/79472453-3f4f9680-7fda-11ea-913b-07e600c33f94.png)

I now realize I may not have been clear about `receive` and `fallback` before, which are somewhat odd. Sorry about that! They are function names, but are special in that they don't require the `function` keyword. They behave exactly like `constructor` in that sense.

**Comment by davidhq** [comment]
Sorry! I also have to get (back to) following Solidity some more.. :)

Hopefully this fixes it:

https://github.com/davidhq/SublimeEthereum/commit/55f492b5894be02deed60b8fcb2e1f8f80686663

Let me know if something is still off !

**Comment by nventuro** [comment]
That did it, thanks!
