### ISSUE TITLE
Solidity 0.6 top-level structs

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#52]
```
pragma solidity 0.6.11;
pragma experimental ABIEncoderV2;

struct MyStruct {
    uint x;
    uint y;
}
```
struct is not colored at all

**Comment by davidhq** [comment]
Hi ! Thank you very much for the report, will look into this and possibly more when summer ends.

**Comment by Tadasu85** [comment]
Any further on this? I am looking at this project to conduct another port for atom and we are now at solidity 0.8.0                                                                                             Is help needed or? Where would a good place to look for a more up to date syntax highlighter?

**Comment by davidhq** [comment]
I'm sorry but it will move completely up-to-date if not tomorrow evening then beginning of next week for sure.. See my answer here: https://github.com/davidhq/SublimeEthereum/issues/54 as well... Today something unexpected happened and my plan to work on this didn't materialize. I think no particular help is needed for now. Examples of what is not working are enough. I will also go through recent Solidity updates to see if something else that was not reported is missing.

I work on this every few months to bring it up to date entirely... but this period actually took a bit long, sorry :|

**Comment by davidhq** [comment]
Will appear on next update

<img width="239" alt="Screenshot 2021-01-16 at 13 12 50" src="https://user-images.githubusercontent.com/3899/104811541-90f0b000-57fc-11eb-84d3-adb2ea52a495.png">

**Comment by Tadasu85** [comment]
No worries man thank you <3

**Comment by davidhq** [comment]
It's deployed in `v1.1.31` ... when SublimeText syncs it should work... 

So currently there are no open issues but I'll still go through some checks and see some solidity updates etc.

If there are no further error reports and after few days of any more possible updates then this is again up-to-date with no open issues.
