### ISSUE TITLE
Solidity 0.6 custom type + immutable

### ISSUE THREAD

**Issue by eMarchenko** [davidhq/SublimeEthereum#53]
![image](https://user-images.githubusercontent.com/7409234/96886868-ad46b000-148c-11eb-98b1-e25264d0b99f.png)
Immutable (constant as well) are not colored, if the variable is of custom type (contract or struct)

**Comment by davidhq** [comment]
<img width="289" alt="Screenshot 2021-01-16 at 13 19 29" src="https://user-images.githubusercontent.com/3899/104811677-7cf97e00-57fd-11eb-89a3-d91b943b4c9c.png">

will publish these changes today after some more checks ...
