### ISSUE TITLE
Add support for do...while loops

### ISSUE THREAD

**Issue by acryptosx** [davidhq/SublimeEthereum#54]
It currently breaks formatting for everything after it.

**Comment by davidhq** [comment]
hi @acryptosx ! Thank you for this... Just yesterday I thought I'm late with adding / checking / fixing two things but it would be nice if anything new has to come, that it would.. and then you sent this :) So now for 3 things it is worth having a nice session and possibly by tomorrow I'll try to get it done.

**Comment by davidhq** [comment]
Hi! I checked and cannot find a case where it break, do... while loops should be already properly supported...

<img width="303" alt="Screenshot 2021-01-16 at 13 09 27" src="https://user-images.githubusercontent.com/3899/104811497-28a1ce80-57fc-11eb-9562-3ebbc8443d41.png">

Please provide a sample to reproduce your issue... thank you

**Comment by acryptosx** [comment]
Hi David, thank you for looking at this so quickly!

The issue is what happens after the do...while loop:

![image](https://user-images.githubusercontent.com/73148363/104813773-3714d800-5846-11eb-9e1d-b739b81b9bfd.png)

**Comment by davidhq** [comment]
Ok great, thank you, I see now... 

will work on it today or at latest monday. I noticed your comment about do...while breaking stuff after it but my sample was not constructed good enough and I didn't manage to reproduce the problem.

**Comment by davidhq** [comment]
Should be fixed in `v1.1.31` once it updates to your SublimeText. 

Please let me know if there are still problems to reopen the ticket.
