### ISSUE TITLE
Incompatibility with different strings specifiers

### ISSUE THREAD

**Issue by kumar-ish** [davidhq/SublimeEthereum#55]
I noticed there's an issue with highlighting a string that's composed of `"`'s and `'`'s in [this](https://github.com/kumar-ish/scaffold-eth/blob/8c562c5fb5a2346fd1257e6d2a273088800f3893/packages/hardhat/contracts/Staker.sol#L55) line on Github; the same thing happens when you switch the `"` and `'`.

Screenshot (Github): 
![image](https://user-images.githubusercontent.com/47245900/107623019-6f240500-6ca4-11eb-86a8-8d056c00c518.png)

It seems to be fine on Sublime though, so I'm not sure what the issue is.

Screenshot (Sublime):
![image](https://user-images.githubusercontent.com/47245900/107623649-641da480-6ca5-11eb-9a76-e74a5589a351.png)

Any ideas?

**Comment by davidhq** [comment]
Yes, GitHub uses different branch https://github.com/davidhq/SublimeEthereum/tree/linguist which is a simpler kind of highlighter (purely regex based) while `master` (SublimeText uses this) is stack + regex... GitHub does not support this..

I'll check if anything can be done simply to ameliorate this... there are many other things that are not optimal in `linguist` version but they are a bit less salient than what you are reporting.... so tnx for report and will look into this next week.

**Comment by davidhq** [comment]
YES! I wasn't able to check it out this past week... if you can do anything, please... if not, I'll check soon

**Comment by davidhq** [comment]
Fixed this https://github.com/davidhq/SublimeEthereum/commit/71aee58f4c97b75f17262ff2540e9dbe7ebc57a0, it was a simple fix, sorry it took some time. It will be live on GitHub when they pick up the changes, it sometimes takes weeks...
I'm finishing some other improvements today and will tag a release for GitHub to pick up on their next syntaxes update when they scan this repo.
