### ISSUE TITLE
Syntax-color does not work in helper

### ISSUE THREAD

**Issue by Willgg** [davidhq/SublimeEthereum#59]
Syntax color does not work in .sol files containing only functions. For instance helpers. 
I guess function have to be within Contract to be recognized.

**Comment by davidhq** [comment]
thank you for this report, will be taken care of next week!

**Comment by davidhq** [comment]
Hi! Sorry, it got a bit delayed but I'm on it, will also tackle / improve some other things not mentioned in two open issues.

Have a happy new year and thank you again for reporting, if there is anything else anyone spots, welcome to point it out

**Comment by davidhq** [comment]
Done in `v1.1.32`, it should update in PackageControl soon, please report back if implementation has any issues
