### ISSUE TITLE
How To Install without error's 

### ISSUE THREAD

**Issue by buschmann** [davidhq/SublimeEthereum#60]
..Still a happy new year ;)

i know sublime only from friends.
Now i try to setup it on my windows, and try to add the grammar for .sol and all around..
// To have it by learning a bit more "easy"..
But in the web all package install how-to`s produce errors and not adding the packages ... :(( 
Perhaps it will be possible to add here in the GitHub into the point "install" a tiny instruction for it ?

**Comment by davidhq** [comment]
Hi ! happy new year! :)

you are right, there could be additional instructions..

can you try this and let me know if it works, will add info to readme later
<img width="460" alt="Screenshot 2022-01-29 at 16 48 01" src="https://user-images.githubusercontent.com/3899/151667479-9e16b19f-3c01-4fd7-9fc5-1095cfdb3fd4.png">
<img width="601" alt="Screenshot 2022-01-29 at 16 48 23" src="https://user-images.githubusercontent.com/3899/151667481-52b18809-78bb-4f56-8349-42fa91410de2.png">

so you need to get to Package Control / Install Package and then type SublimeEthereum and install the package.

**Comment by buschmann** [comment]
Oh Cool let me check..:)

No not in the list ..

[image: image.png]


Am Sa., 29. Jan. 2022 um 16:50 Uhr schrieb davidhq ***@***.***

**Comment by davidhq** [comment]
Sorry, try just with "Ethereum" ! Is this in the list?

**Comment by buschmann** [comment]
...YESS++  it's in..but why now and not 2h before ... I hate computers.. 😂
THANKS a lot, now i can try to learn a bit of solidity,
to form a construct with 100 contracts ... I hate computer games.. 🙈

[image: image.png]

Am Sa., 29. Jan. 2022 um 18:35 Uhr schrieb davidhq ***@***.***
>:

> Sorry, try just with "Ethereum" ! Is this in the list?
>

**Comment by davidhq** [comment]
Ok awesome! I'll add explicit install instructions later today so it's easier.

I think 2h ago in same steps should also work, maybe you didn't do it in the same way, Package Control can be confusing at first. Maybe you chose "List packages" instead of Install... now that you have Ethereum package installed it's in List packages and not in Install enaymore. If you uninstall it it'll be again in Install list but not in List packages

**Comment by buschmann** [comment]
..perfect ... nice paper & pencil are important for everyone to have ;)
For me.. please add  ALEXA  to type contracts from buzzwords ++ 😬

Am Sa., 29. Jan. 2022 um 18:58 Uhr schrieb davidhq ***@***.***
>:

> Ok awesome! I'll add explicit install instructions later today so it's
> easier.
>
> I think 2h ago in same steps should also work, maybe you didn't do it in
> the same way, Package Control can be confusing at first. Maybe you chose
> "List packages" instead of Install... now that you have Ethereum package
> installed it's in List packages and not in Install enaymore. If you
> uninstall it it'll be again in Install list but not in List packages
>

**Comment by davidhq** [comment]
Alexa / A.I. integration next week.
