### ISSUE TITLE
Package Not In List for Sublime 4 MacOS

### ISSUE THREAD

**Issue by woodydeck** [davidhq/SublimeEthereum#66]
There's no Ethereum package currently in the Sublime Text 4 menu. Additionally, the last update breaks JS highlighting and it freezes. TypeScript seems to be ok for highlighting things. I've been bugging Sublime to add default support for Solidity for a while.

Best of luck!

**Comment by davidhq** [comment]
Hi are you sure?

<img width="496" alt="Screenshot 2023-01-10 at 13 32 41" src="https://user-images.githubusercontent.com/3899/211552715-71fcb89e-3c89-4021-bbbb-76c983538eaf.png">
