### ISSUE TITLE
Quotes are not escaped inside of strings

### ISSUE THREAD

**Issue by DaniPopes** [davidhq/SublimeEthereum#68]
Single or double quotes are not escaped inside of strings, leaving the rest of the string without highlighting.

#### solidity

```solidity
string single = ' \' rest ';
string double = " \" rest ";
```

#### yul

```yul
single := ' \' rest ';
double := " \" rest ";
```
#### vyper

```vyper
single: String[8] = ' \' rest ';
double: String[8] = " \" rest ";
```

**Comment by davidhq** [comment]
Interesting, thank you! Will check end of next week and confirm the issue ....
just going somewhere without internet early tomorrow, cannot even check now.. but will be worked on soon.

**Comment by davidhq** [comment]
hi, it's fixed in stack based sublimetext highlighter, still having trouble making a good solution for purely regex based highlighters used at github... thank you again for reporting this, I confirm it's a problem and as said, trying to make it work for github

**Comment by davidhq** [comment]
managed to make it work https://github.com/davidhq/SublimeEthereum/commit/98e4c26e6e7236eca752c2f3d0c70f076c0598df 

let's wait for GitHub to pickup the change on the next linguist release, might be even couple of month, they had a release last month https://github.com/github-linguist/linguist/tags

I will also verify on some github examples then but testing inside sublimetext shows that it's solved

<img width="450" alt="Screenshot 2023-07-28 at 12 31 36" src="https://github.com/davidhq/SublimeEthereum/assets/3899/0f36d0b0-c200-4ae5-b838-02a73a93decf">
