### ISSUE TITLE
Request: snippets

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [davidhq/SublimeEthereum#7]
I love snippets. There are a few useful ones in Vim format [here](https://gist.github.com/nemild/98343ce6b16b747788bc) and I'd be happy to implement them inside the SublimeEthereum package.

**Comment by davidhq** [comment]
hey! you can do it, sure.. I will accept the pull request and maybe help later

I have to finally bring the syntax up to date in the next days

**Comment by davidhq** [comment]
Closing this...
