### ISSUE TITLE
Quotes inside strings cause incorrect string termination

### ISSUE THREAD

**Issue by fafrd** [davidhq/SublimeEthereum#72]
In https://github.com/davidhq/SublimeEthereum/issues/68, the issue with escaped quotes such as `\"` and `\'` was fixed.

However Solidity also supports single quotes inside of double quotes, and double quotes inside of single quotes. This is misinterpreted by the syntax highlighter as ending the string early.

For example, in [this file](https://github.com/ondoprotocol/tokenized-funds/blob/main/contracts/token/CashKYCSenderReceiver.sol) a large swath of the syntax is highlighted incorrectly as a result:
<img width="599" alt="Screenshot 2024-03-29 at 9 36 21 AM" src="https://github.com/davidhq/SublimeEthereum/assets/5905628/83a179b9-fbaf-47eb-8894-7d686be1d109">

**Comment by fafrd** [comment]
I think this diff will fix it, but I don't have a good way to test this, can you try it out?

- Remove `scope: string.quoted`. Previously, when the end of the string was matched (the terminating quote), it was still being marked with the string.quoted scope, but this technically causes the surrounding quotes to be considered part of the string itself, which is inaccurate. Now only the inner part should be considered a string for highlighting purposes.
- Match _any_ escaped character, not just quotes/single, just sort of cleanup but probably not strictly necessary
- `match: [^\"\\]+` and `match: [^\'\\]+`: Match everything except ' and \ for a "string", and match everything except " and \ for 'string'. 

```diff
diff --git a/Solidity.sublime-syntax b/Solidity.sublime-syntax
index 5f11973..5e25635 100644
--- a/Solidity.sublime-syntax
+++ b/Solidity.sublime-syntax
@@ -105,26 +105,20 @@ contexts:
   string-contents-double-quote:
     - meta_include_prototype: false # don't start a comment inside string
     - match: \"
-      scope: string.quoted
       pop: true
-    - match: \\"
-      scope: constant.character.escape
-    - match: \\'
+    - match: \\.
       scope: constant.character.escape
-    - match: \S
+    - match: [^\"\\]+ # Match any character except a backslash or double quote
       scope: string.quoted
     - include: eol-pop

   string-contents-single-quote:
     - meta_include_prototype: false # don't start a comment inside string
     - match: \'
-      scope: string.quoted
       pop: true
-    - match: \\"
-      scope: constant.character.escape
-    - match: \\'
+    - match: \\.
       scope: constant.character.escape
-    - match: \S
+    - match: [^\'\\]+ # Match any character except a backslash or single quote
       scope: string.quoted
     - include: eol-pop
```

**Comment by davidhq** [comment]
Hi! Thank you very much and sorry for the late response...

I confirm the issue:
![Screenshot 2024-04-16 at 21 28 48](https://github.com/davidhq/SublimeEthereum/assets/3899/98cbbcd8-cc84-4d19-8bf4-f407a0b45111)

but the fix has to be done on the [https://github.com/davidhq/SublimeEthereum/tree/linguist](Linguist) branch which GitHub uses... Master is more advanced highlighter with stack for sublimetext only. Here there is no issue in the first place:

![Screenshot 2024-04-16 at 21 29 22](https://github.com/davidhq/SublimeEthereum/assets/3899/83219004-6d87-460e-a4c2-0d9da0cfd3dc)

I will look into it over this and next week and try to find a solution, maybe I can use some of your ideas although you applied them to the sublime-specific highlighter... some things are impossible to do with simple regex highlighter which GitHub supports but I think and hope this is not one such issue... will know shortly.. thank you again

**Comment by davidhq** [comment]
Hi, I think I fixed this, will test some more... it was an easy fix though:

before:

![Screenshot 2024-04-25 at 18 54 04](https://github.com/davidhq/SublimeEthereum/assets/3899/6dc7e569-af76-4dea-8937-6df9f718eefd)

after:

![Screenshot 2024-04-25 at 18 54 27](https://github.com/davidhq/SublimeEthereum/assets/3899/0a19a72d-1c57-4c88-8d2f-c7b1dc238404)

I will push the code to github and only every few months GitHub actually picks the changes so it might take some weeks to reflect the change... thank you for reporting

**Comment by fafrd** [comment]
Thank you!
