### ISSUE TITLE
Corrections: Get rid of hash, add support for fixed/ufixed

### ISSUE THREAD

**Issue by VoR0220** [davidhq/SublimeEthereum#9]
this line 

`- match: \b(address|string\d*|bytes\d*|int\d*|uint\d*|bool|hash\d*)\b(?:\s+(?:indexed\s+)?([A-Za-z_]\w*)\s*[,\)])?`

should be stripped of hash and also should have added functionality for all (u)fixedMxN types.

**Comment by davidhq** [comment]
Fixed by @ralph-pichler in v0.9.57
